environment:
  global:
    MESON_OPTS: '-Dtest_expect_fail=true --unity on'
    CYG_ARCH: x86_64
    CYG_BASE: 'C:\cygwin64'

install:
  - '"%CYG_BASE%\setup-%CYG_ARCH%.exe" --quiet-mode --no-shortcuts --packages bash,cygutils-extra,cygwin-devel,gettext-devel,git,gcc-core,gcc-g++,libboost-devel,libintl-devel,make,meson,ninja,python3'
  - '"%CYG_BASE%\bin\cygcheck" -dc'
  - '"%CYG_BASE%\bin\bash" -lc "id"'
  - '"%CYG_BASE%\bin\bash" -lc "cygdrop id"'
  - '"%CYG_BASE%\bin\bash" -lc "mount"'

build_script:
  - '"%CYG_BASE%\bin\bash" -lc "cd \"$APPVEYOR_BUILD_FOLDER\" && make"'
  - '"%CYG_BASE%\bin\bash" -lc "cd \"$APPVEYOR_BUILD_FOLDER\" && make DESTDIR=\"`pwd`/build/install\" install"'

test_script:
  - '"%CYG_BASE%\bin\bash" -lc "cd \"$APPVEYOR_BUILD_FOLDER\" && make check"'
  - '"%CYG_BASE%\bin\bash" -lc "cd \"$APPVEYOR_BUILD_FOLDER\" && cygdrop make check"'
