language: cpp

dist: xenial
addons:
  apt:
    packages:
      - bash
      - binutils
      - coreutils
      - diffutils
      - findutils
      - gcc
      - libboost-dev
      - libboost-filesystem-dev
      - libboost-program-options-dev
      - libboost-system-dev
      - make
      - python3
      - python3-pip
      - python3-setuptools
      - python3-sphinx

install:
  - pip3 install --user --upgrade pip setuptools
  - pip3 install --user meson ninja

script:
  - make check
  - make -C docs man html
