language: cpp

sudo: false

matrix:
  include:
    - name: Documentation
      os: linux
      dist: xenial
      env: BUILD=docs

    - name: GCC 5
      os: linux
      dist: xenial
      addons:
        apt:
          sources: [ubuntu-toolchain-r-test]
          packages: [libboost-filesystem-dev, libboost-program-options-dev, python3-pip, gcc-5, g++-5]
      env: BUILD=app C_COMPILER=gcc-5 CXX_COMPILER=g++-5

    - name: GCC 6
      os: linux
      dist: xenial
      addons:
        apt:
          sources: [ubuntu-toolchain-r-test]
          packages: [libboost-filesystem-dev, libboost-program-options-dev, python3-pip, gcc-6, g++-6]
      env: BUILD=app C_COMPILER=gcc-6 CXX_COMPILER=g++-6

    - name: GCC 7
      os: linux
      dist: xenial
      addons:
        apt:
          sources: [ubuntu-toolchain-r-test]
          packages: [libboost-filesystem-dev, libboost-program-options-dev, python3-pip, gcc-7, g++-7]
      env: BUILD=app C_COMPILER=gcc-7 CXX_COMPILER=g++-7

    - name: GCC 8
      os: linux
      dist: xenial
      addons:
        apt:
          sources: [ubuntu-toolchain-r-test]
          packages: [libboost-filesystem-dev, libboost-program-options-dev, python3-pip, gcc-8, g++-8]
      env: BUILD=app C_COMPILER=gcc-8 CXX_COMPILER=g++-8

    - name: Clang 3.9
      os: linux
      dist: xenial
      addons:
        apt:
          sources: [ubuntu-toolchain-r-test]
          packages: [libboost-filesystem-dev, libboost-program-options-dev, python3-pip, clang-3.9, llvm-3.9-dev]
      env: BUILD=app C_COMPILER=clang-3.9 CXX_COMPILER=clang++-3.9

    - name: Clang 4.0
      os: linux
      dist: xenial
      addons:
        apt:
          sources: [ubuntu-toolchain-r-test]
          packages: [libboost-filesystem-dev, libboost-program-options-dev, python3-pip, clang-4.0, llvm-4.0-dev]
      env: BUILD=app C_COMPILER=clang-4.0 CXX_COMPILER=clang++-4.0

    - name: Clang 5.0
      os: linux
      dist: xenial
      addons:
        apt:
          sources: [ubuntu-toolchain-r-test]
          packages: [libboost-filesystem-dev, libboost-program-options-dev, python3-pip, clang-5.0, llvm-5.0-dev]
      env: BUILD=app C_COMPILER=clang-5.0 CXX_COMPILER=clang++-5.0

    - name: Clang 6.0
      os: linux
      dist: xenial
      addons:
        apt:
          sources: [ubuntu-toolchain-r-test]
          packages: [libboost-filesystem-dev, libboost-program-options-dev, python3-pip, clang-6.0, llvm-6.0-dev]
      env: BUILD=app C_COMPILER=clang-6.0 CXX_COMPILER=clang++-6.0

install:
  - if [ "$BUILD" = "app" ]; then
      pip3 install --user --upgrade pip;
      pip3 install --user setuptools;
      pip3 install --user meson ninja;
    fi
  - pip3 install --user Sphinx;

script:
  - if [ "$BUILD" = "app" ]; then
      make CC=$C_COMPILER CXX=$CXX_COMPILER distclean check;
    elif [ "$BUILD" = "docs" ]; then
      make -C docs man html linkcheck;
    fi

notifications:
  email:
    recipients:
      - secure: "fFBhVhwdnAIZo815XjBtIa7TIKr29PTcE6m6pNhF3guXzLnsJZsTx/1nS7TiI4hLt+LleogPc5Sf/q+gPd+LTOYMSN9R8E93r0VZGu9tk50FYzBhvTgw7Bj4BLYMW2UmFqqk6MGGHiaevDTGx2y8+sIDHfoIL/ZtkLAsxOVobBfSKwtyR2EMNkN+t7IWeYoHJfBN3Zin3slgwluKiCEYp9htRK8NS64HgU+HU8CPx7jqp5L/yzGkT6sOLNOop+6GehfZ9srwBR/ZgVuotjiVwqitzRA0wtXhrZQ3k+AsLdfZaIp2VPyn6QnezCr5V9vQkQYdwaWeG1zSEtCJ3zsGi34ch3BXs1vdsokOVJdr3TCJvFHr4ClA9qsoiLGq+kp/WlWNneyXOYifsMA9Ib5INZ3fO2ehxTDI81rIKh5JrNCjRifXM4alCpKd7Wrg/KSgapiYga9IqC3rIUoVkhs/+zHDb4XrRyQolFLnzVlQQ+hGacNz9QMuwi4Hhww532A8rv2tRN22bPdmFvOdOVhDJTwcGuesw7Zud7/lwwiEte+8uWnx+/9h1nN1Y843VLJqAG59/7zNxyAGBwVp1M6Otd36VDvBKDtE+F6kE6HtJdsExsvyqvKCxX4rQ9JmpCKNRaS2xeKsZ2XKfF0Iw/wj5wsovXk8cSjA3GEY+SjG48I="
