#!/bin/sh
echo "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor" >&2
echo "incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis" >&2
echo "nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat." >&2
echo "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore" >&2
echo "eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt" >&2
echo "in culpa qui officia deserunt mollit anim id est laborum." >&2
