#!/bin/sh
echo "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor" >&1
echo "incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis" >&1
echo "nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat." >&1
echo "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore" >&1
echo "eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt" >&1
echo "in culpa qui officia deserunt mollit anim id est laborum." >&1

echo "Bacon ipsum dolor amet laborum sirloin bresaola beef ham hock et venison" >&1
echo "frankfurter andouille enim jerky pastrami cow. Jerky beef dolor commodo," >&1
echo "pancetta dolore dolore. Consectetur aliqua dolor frankfurter, sed laboris" >&1
echo "commodo fatback meatball proident. Do commodo tongue jerky doner. Pork loin" >&1
echo "occaecat sunt swine deserunt. Proident turkey dolor est duis qui jowl magna" >&1
echo "elit ham hock enim boudin brisket laborum t-bone. Drumstick sirloin pig." >&1

echo "Veggies es bonus vobis, proinde vos postulo essum magis kohlrabi welsh onion" >&2
echo "daikon amaranth tatsoi tomatillo melon azuki bean garlic." >&2
echo "Gumbo beet greens corn soko endive gumbo gourd. Parsley shallot courgette" >&2
echo "tatsoi pea sprouts fava bean collard greens dandelion okra wakame tomato." >&2
echo "Dandelion cucumber earthnut pea peanut soko zucchini." >&2

echo "Asiatic canthigaster central chum crappie cuckoo denticle grunion jawfish" >&1
echo "knifefish longjaw major mosshead mullet redside remora sandfish seahorse" >&1
echo "slimehead tigerperch titan trumpetfish vendace wels woody. Aholehole" >&1
echo "anglerfish bluegill bobtail bream common daggertooth dottyback galjoen giant" >&1
echo "gombessa halosaur horse john kahawai mail-cheeked north ponyfish porgy ribbon" >&1
echo "righteye saury spiderfish surgeonfish sweeper velvet-belly walleye. Albacore" >&1
echo "barbeled bristlemouth burma croaker duck eel-catfish ghost kaluga mudminnow" >&1
echo "mustache new nurse pleco pufferfish ratfish sardine sauger smooth snoek" >&1
echo "soldierfish stingfish. Blacksmelt carpsucker dempsey dusky fish flagfish" >&1
echo "four-eyed lamprey leopard long-whiskered mexican mrigal pelagic rockweed" >&1
echo "sailbearer squarehead straptail weasel." >&1

echo "Bathygnathus crosbysaurus giganotosaurus gyposaurus sinensis heishansaurus" >&2
echo "ischisaurus jaxartosaurus laornis lourinhanosaurus microceratops nanotyrannus" >&2
echo "ornithoides pachysuchus pararhabdodon probably velociraptor rocasaurus" >&2
echo "volkheimeria zanabazar." >&2
exit 0
