#!/bin/sh
echo "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor" >&1 || exit 31
echo "Bacon ipsum dolor amet laborum sirloin bresaola beef ham hock et venison" >&2 || exit 32
echo "incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis" >&1 || exit 31
echo "frankfurter andouille enim jerky pastrami cow. Jerky beef dolor commodo," >&2 || exit 32
echo "nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat." >&1 || exit 31
echo "pancetta dolore dolore. Consectetur aliqua dolor frankfurter, sed laboris" >&2 || exit 32
echo "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore" >&1 || exit 31
echo "commodo fatback meatball proident. Do commodo tongue jerky doner. Pork loin" >&2 || exit 32
echo "eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt" >&1 || exit 31
echo "occaecat sunt swine deserunt. Proident turkey dolor est duis qui jowl magna" >&2 || exit 32
echo "in culpa qui officia deserunt mollit anim id est laborum." >&1 || exit 31
echo "elit ham hock enim boudin brisket laborum t-bone. Drumstick sirloin pig." >&2 || exit 32
exit 42
